<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <ApplicationIcon>Icon\ScaleformEncoder.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Icon\ScaleformEncoder.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sofdec2EncoderControl\Sofdec2EncoderControl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>