/**************************************************************************

Filename    :   Video_VideoPC.h
Content     :   GFx video for Windows based PC
Created     :   Sep 2009
Changed    : March 10, 2026
Authors     :   Maxim Didenko, Vladislav Merker (2008.6.4) [is cri movie 3.50]
                    MonstroFil, Claude(2026.3) [Changed To Cri Mana 2019 From Criware SDK 2.19.03, From Github Author]
                    FINALZ-27980 [To Integration]

Copyright   :   Copyright 2011 Autodesk, Inc. All Rights reserved.
                     Copyright 2026 Final Game Production Inc. All Rights reserved.

TIPS          :  This Version Is Not Stable To Open The New Sample Like GFL2 Exilium .usm
                      (GFL2 Exilium Game Video Has No Crypto, ... Encoding Is VP9?H.264?H.265, Created By Sofdec2 Encoding Wizard) File Cuz It's Has Crash.
                    But Sofdec2 Viewer Can Open It (2.09.02 [For Original SDK 2.19.03] Can Do It).
                    Other .usm (Such PS3 Game Kung Fu Panda 2 .usm File Generated By ScaleformVideoEncoder, Is MPEG1-USMs) File Is Normal.

                    The Reason When Open GFL2 Exilium .usm Video File Is:
                    An unhandled exception occurred at 0x0000000140637401 (in GFxPlayer_D3D11_Release_Static.exe, USE-AFTER-FREE Problem): 0xC0000005:
                    Access violation when reading location 0x0000000000000008.

					Another Problem Is Scaleform Official Named Sample_VP9.usm From CRIWARE Official SDK 2.19.03, Is Same Reason LIke GFL2 Exilium .usm File,
                    It's Crash For USE-AFTER-FREE Too.

                    THE TYPICAL REASON OF THIS PROBLEM IS:
					When Open A New Sample Like GFL2 Exilium .usm File, The Video Reader Will Be Created By Criware SDK, But The Video Reader Is NULL,
					... ENDOCING THREADS NUMBER IS 0, ... And When The Video Reader Is Used To Read The Video Data, It Will Cause Access Violation And Crash.

                    Should Be Fix It Is Requirments.

                    This Criware SDK Will Be Removed In Scaleform 5.0 (After 2030) Stable Version, And Change To FFMpeg,
                    FINAL VIDEO(FINAL ENGINE), A SelectaVision HDRVIDEOS Persensation(.264-.268), And More Support Video As Everyone Seen.

Use of this software is subject to the terms of the Autodesk license
agreement provided at the time of installation or download, or which
otherwise accompanies this software in either electronic or hard copy form.

**************************************************************************/

#ifndef INC_GFX_VIDEOPC_H
#define INC_GFX_VIDEOPC_H

#include "Video/Video_Video.h"

#if defined(GFX_ENABLE_VIDEO) && defined(SF_OS_WIN32)

#define MAX_VIDEO_DECODING_THREADS 3
#define DEFAULT_VIDEO_DECODING_AFFINITY_MASK 0xFFFFFFFF

namespace Scaleform { namespace GFx { namespace Video {

//////////////////////////////////////////////////////////////////////////
//

class VideoPC : public Video
{
public:
    // The first parameter specifies ActionScript VM support: AS2, AS3 or both.
    // The second parameter specifies priority of the video decoding threads.
    // The third, specifies the number of threads which will be used for video
    // decoding (maximum is 3). And forth parameter is an array of the affinity
    // masks for each decoding thread.
    VideoPC(const VideoVMSupport& vmSupport,
            Thread::ThreadPriority decodingThreadsPriority = Thread::NormalPriority, 
            int decodingThreadsNumber = MAX_VIDEO_DECODING_THREADS,
            UInt32* affinityMask = NULL);

    // PC specific settings such as number and priority of decoding threads
    // and affinity mask for the video player.
    virtual void ApplySystemSettings(VideoPlayer* pvideoPlayer);
    virtual void ApplySystemSettings(VideoDecoder*) {}
    virtual void ApplySystemSettings(VideoReaderConfig*) {}

private:
    int     DecodingThreadNumber;
    UInt32  AffinityMask[MAX_VIDEO_DECODING_THREADS];
};

}}} // Scaleform::GFx::Video

#endif // GFX_ENABLE_VIDEO && SF_OS_WIN32

#endif // INC_GFX_VIDEOPC_H
