/**************************************************************************

Filename    :   Video_CriMvSystemTimer.cpp
Content     :   Video system timer (simplified for CRI Mana 2019)
Created     :   June 4, 2008
Changed    :   March 10, 2026
Authors     :   Maxim Didenko, Vladislav Merker (2008.6.4) [is cri movie 3.50]
                    MonstroFil, Claude(2026.3) [Changed To Cri Mana 2019 From Criware SDK 2.19.03, From Github Author]
                    FINALZ-27980 [To Integration]

Copyright   :   Copyright 2011 Autodesk, Inc. All Rights reserved.
                     Copyright 2026 Final Game Production Inc. All Rights reserved.

TIPS          :  This Version Is Not Stable To Open The New Sample Like GFL2 Exilium .usm
                      (GFL2 Exilium Game Video Has No Crypto, ... Encoding Is VP9?H.264?H.265, Created By Sofdec2 Encoding Wizard) File Cuz It's Has Crash.
                    But Sofdec2 Viewer Can Open It (2.09.02 [For Original SDK 2.19.03] Can Do It).
                    Other .usm (Such PS3 Game Kung Fu Panda 2 .usm File Generated By ScaleformVideoEncoder, Is MPEG1-USMs) File Is Normal.

                    The Reason When Open Sample Like GFL2 Exilium .usm Video File Is:
                    An unhandled exception occurred at 0x0000000140637401 (in GFxPlayer_D3D11_Release_Static.exe, USE-AFTER-FREE Problem): 0xC0000005:
                    Access violation when reading location 0x0000000000000008.

                    Should Be Fix It Is Requirments.

                    This Criware SDK Will Be Removed In Scaleform 5.0 (After 2030) Stable Version, And Change To FFMpeg,
                    FINAL VIDEO(FINAL ENGINE), A SelectaVision HDRVIDEOS Persensation(.264-.268), And More Support Video As Everyone Seen.

Use of this software is subject to the terms of the Autodesk license
agreement provided at the time of installation or download, or which
otherwise accompanies this software in either electronic or hard copy form.

**************************************************************************/

#include "GFxConfig.h"
#ifdef GFX_ENABLE_VIDEO

#include "Kernel/SF_Timer.h"
#include "Video/Video_CriMvSystemTimer.h"

namespace Scaleform { namespace GFx { namespace Video {

//////////////////////////////////////////////////////////////////////////
// SystemTimerSyncObject — used for external synchronization with Mana's
// MANUAL timer mode when a SyncObject is provided by the application.

void SystemTimerSyncObject::Start(void)
{
    time_count = 0;
    time_unit = Timer::GetRawFrequency();
    total_count = 0;
    pause_flag = false;
    IsRunning = true;
    StartTicks = Timer::GetRawTicks();
}

void SystemTimerSyncObject::Stop(void)
{
    StopTicks = Timer::GetRawTicks();
    IsRunning = false;
    total_count = 0;
}

void SystemTimerSyncObject::Pause(bool sw)
{
    if (pause_flag == sw)
        return;

    if (sw)
    {
        StopTicks = Timer::GetRawTicks();
        IsRunning = false;
        time_count = StopTicks - StartTicks;
        total_count += time_count;
    }
    else
    {
        IsRunning = true;
        StartTicks = Timer::GetRawTicks();
    }
    pause_flag = sw;
}

void SystemTimerSyncObject::GetTime(UInt64 *count, UInt64 *unit)
{
    *unit = Timer::GetRawFrequency();

    if (pause_flag)
    {
        *count = total_count;
    }
    else
    {
        if (IsRunning)
        {
            UInt64 ccnt = Timer::GetRawTicks();
            *count = (ccnt - StartTicks) + total_count;
        }
        else
        {
            *count = total_count;
        }
    }
}

}}} // Scaleform::GFx::Video

#endif // GFX_ENABLE_VIDEO
